"""
pdf_generator.py — Professional PDF generation module.

Creates well-formatted, downloadable PDF documents from the
generated article content using fpdf2.
"""

import os
import re
import textwrap
from datetime import datetime
from fpdf import FPDF

import config


class ArticlePDF(FPDF):
    """
    Custom PDF class with header, footer, and article-specific formatting.

    Uses built-in PDF core fonts (Helvetica) to avoid external font dependencies.
    """

    def __init__(self, title: str = "Article"):
        super().__init__()
        self.article_title = title
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        """Render page header with a colored bar and app branding."""
        # Gradient-style header bar
        self.set_fill_color(79, 70, 229)  # Indigo
        self.rect(0, 0, 210, 12, "F")

        # Branding text
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(255, 255, 255)
        self.set_y(3)
        self.cell(0, 6, "Generated by YouTube to Insightful Article & PDF", align="C")

        # Reset position for body content
        self.set_y(18)

    def footer(self):
        """Render page footer with page number and generation date."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def add_title_page(self, title: str, video_url: str, summary: str):
        """
        Create a visually appealing title page.

        Args:
            title:     Article title.
            video_url: Original YouTube URL.
            summary:   Short summary of the article.
        """
        self.add_page()
        self.ln(30)

        # Main title
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(31, 41, 55)
        self.multi_cell(0, 12, self._safe_text(title), align="C")
        self.ln(8)

        # Decorative divider
        self.set_draw_color(79, 70, 229)
        self.set_line_width(1)
        x_center = self.w / 2
        self.line(x_center - 30, self.get_y(), x_center + 30, self.get_y())
        self.ln(8)

        # Metadata
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(107, 114, 128)
        date_str = datetime.now().strftime("%B %d, %Y")
        self.cell(0, 6, f"Generated on {date_str}", align="C")
        self.ln(5)
        self.cell(0, 6, f"Source: {video_url[:80]}", align="C")
        self.ln(15)

        # Summary box
        self.set_fill_color(243, 244, 246)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(55, 65, 81)

        # Calculate box dimensions
        summary_clean = self._safe_text(summary)
        self.set_x(20)
        self.multi_cell(170, 6, summary_clean, border=0, fill=True)

    def add_section(self, heading: str, body: str, heading_level: int = 1):
        """
        Add a content section with heading and body text.

        Args:
            heading:       Section heading text.
            body:          Section body text (supports basic markdown).
            heading_level: 1 for main heading, 2 for subheading.
        """
        self.ln(6)

        # Section heading
        if heading_level == 1:
            self.set_font("Helvetica", "B", 16)
            self.set_text_color(31, 41, 55)
            # Indigo accent bar
            self.set_fill_color(79, 70, 229)
            self.rect(self.l_margin, self.get_y(), 3, 8, "F")
            self.set_x(self.l_margin + 6)
        else:
            self.set_font("Helvetica", "B", 13)
            self.set_text_color(55, 65, 81)

        self.multi_cell(0, 8, self._safe_text(heading))
        self.ln(3)

        # Body text — process paragraph by paragraph
        self.set_font("Helvetica", "", 10)
        self.set_text_color(75, 85, 99)

        paragraphs = body.split("\n")
        for para in paragraphs:
            para = para.strip()
            if not para:
                self.ln(3)
                continue

            # Handle bullet points
            if para.startswith(("•", "-", "*")):
                clean = para.lstrip("•-* ").strip()
                self.set_x(self.l_margin + 6)
                bullet_text = f"  {chr(8226)}  {self._safe_text(clean)}"
                self.multi_cell(self.w - self.l_margin - self.r_margin - 6, 6, bullet_text)
                self.ln(1)
            # Handle markdown headings in article body
            elif para.startswith("###"):
                clean = para.lstrip("# ").strip()
                self.set_font("Helvetica", "B", 11)
                self.set_text_color(55, 65, 81)
                self.multi_cell(0, 7, self._safe_text(clean))
                self.set_font("Helvetica", "", 10)
                self.set_text_color(75, 85, 99)
                self.ln(2)
            elif para.startswith("##"):
                clean = para.lstrip("# ").strip()
                self.set_font("Helvetica", "B", 13)
                self.set_text_color(31, 41, 55)
                self.multi_cell(0, 8, self._safe_text(clean))
                self.set_font("Helvetica", "", 10)
                self.set_text_color(75, 85, 99)
                self.ln(2)
            else:
                # Regular paragraph — strip markdown bold/italic
                clean = re.sub(r"\*\*(.*?)\*\*", r"\1", para)
                clean = re.sub(r"\*(.*?)\*", r"\1", clean)
                self.multi_cell(0, 6, self._safe_text(clean))
                self.ln(2)

    def _safe_text(self, text: str) -> str:
        """
        Make text safe for PDF rendering.
        Replaces characters that are not supported by the core Helvetica font.
        """
        # Replace common Unicode characters with ASCII equivalents
        replacements = {
            "\u2018": "'", "\u2019": "'",   # Smart single quotes
            "\u201c": '"', "\u201d": '"',   # Smart double quotes
            "\u2013": "-", "\u2014": "--",  # En/em dashes
            "\u2026": "...",                # Ellipsis
            "\u2022": chr(8226),            # Bullet (supported in latin-1)
            "\u00a0": " ",                  # Non-breaking space
        }
        for old, new in replacements.items():
            text = text.replace(old, new)

        # Encode to latin-1, replacing any remaining unsupported characters
        return text.encode("latin-1", errors="replace").decode("latin-1")


def create_pdf(
    title: str,
    summary: str,
    article: str,
    insights: str,
    video_url: str,
    video_id: str,
) -> str:
    """
    Generate a professional PDF document from the generated content.

    Args:
        title:     Article title.
        summary:   Article summary.
        article:   Full article text.
        insights:  Key insights (bullet points).
        video_url: Original YouTube URL.
        video_id:  YouTube video ID (used in filename).

    Returns:
        The absolute path to the generated PDF file.
    """
    pdf = ArticlePDF(title=title)
    pdf.alias_nb_pages()

    # Page 1: Title page with summary
    pdf.add_title_page(title, video_url, summary)

    # Page 2+: Full article
    pdf.add_page()
    pdf.add_section("Full Article", article, heading_level=1)

    # Key Insights section
    pdf.add_section("Key Insights", insights, heading_level=1)

    # Save to outputs directory
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = re.sub(r"[^\w\s-]", "", title)[:50].strip().replace(" ", "_")
    filename = f"{safe_title}_{timestamp}.pdf"
    filepath = os.path.join(config.OUTPUT_DIR, filename)

    pdf.output(filepath)
    return filepath
